# Generated by Django 5.2.4 on 2025-08-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_des_product_description_remove_cart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='items', through='app.CartItem', to='app.product'),
        ),
    ]
